// src/game/maps/map-types.ts
// Shared types for the tilemap layer.
// Pure data shapes — no Phaser, no game-logic imports.
//
// Maps are authored as Tiled 1.10 JSON (generated by
// tools/asset-pipeline/compose-maps.mjs and editable in the Tiled editor).
// This file describes both the on-disk Tiled shapes we read and the runtime
// model map-loader.ts produces from them.

import type { Rect } from '../shared/movement-system';
export type { Rect };

// ─── Canonical layer names ────────────────────────────────────────────────────

/**
 * Tile layers, in render order (back to front). A map may omit any of them.
 * Foreground draws above the player; everything else draws below.
 *
 * Note Water sits BELOW Paths, which inverts the more common listing order.
 * That is deliberate: a bridge is a path crossing a river, so the path tiles
 * have to be able to draw over the water tiles.
 */
export const TILE_LAYERS = [
  'Ground',
  'Terrain',
  'Water',
  'Paths',
  'DecorationBelow',
  'DecorationAbove',
  'Foreground',
] as const;
export type TileLayerName = (typeof TILE_LAYERS)[number];

/** Tile layers that render above the player rather than below. */
export const ABOVE_PLAYER_LAYERS: readonly TileLayerName[] = ['Foreground'];

/**
 * Object layers. These are gameplay data and are never rendered directly;
 * `Objects` and `NPCs` are turned into sprites, the rest into pure geometry.
 */
export const OBJECT_LAYERS = [
  'Objects',
  'Collision',
  'EncounterZones',
  'Triggers',
  'SpawnPoints',
  'NPCs',
] as const;
export type ObjectLayerName = (typeof OBJECT_LAYERS)[number];

// ─── Tiled JSON (the subset we consume) ───────────────────────────────────────

export interface TiledProperty {
  name: string;
  type: string;
  value: string | number | boolean;
}

export interface TiledObject {
  id: number;
  name: string;
  type?: string;
  x: number;
  y: number;
  width: number;
  height: number;
  point?: boolean;
  visible?: boolean;
  properties?: TiledProperty[];
}

export interface TiledTileLayer {
  id: number;
  name: string;
  type: 'tilelayer';
  width: number;
  height: number;
  data: number[];
  opacity: number;
  visible: boolean;
}

export interface TiledObjectLayer {
  id: number;
  name: string;
  type: 'objectgroup';
  objects: TiledObject[];
}

export type TiledLayer = TiledTileLayer | TiledObjectLayer;

export interface TiledTilesetTile {
  id: number;
  properties?: TiledProperty[];
}

export interface TiledTileset {
  firstgid: number;
  name: string;
  image: string;
  imagewidth: number;
  imageheight: number;
  columns: number;
  tilecount: number;
  tilewidth: number;
  tileheight: number;
  tiles?: TiledTilesetTile[];
}

export interface TiledMap {
  width: number;
  height: number;
  tilewidth: number;
  tileheight: number;
  layers: TiledLayer[];
  tilesets: TiledTileset[];
  properties?: TiledProperty[];
}

// ─── Runtime model ────────────────────────────────────────────────────────────

/**
 * What kind of place a map is. Controls encounters, HUD, and whether the
 * game menu offers saving.
 *   travel   — the overworld you cross between locations; random encounters.
 *   field    — a walkable location such as a forest; random encounters.
 *   town     — a settlement; no encounters, NPCs and shops.
 *   interior — inside a building; no encounters, no world exit.
 */
export type MapKind = 'travel' | 'field' | 'town' | 'interior';

/** What a trigger does when the player activates or enters it. */
export type TriggerKind =
  | 'map'      // move to another map at a named spawn point
  | 'battle'   // start a scripted battle
  | 'dialogue' // run a dialogue sequence
  | 'save'     // save point
  | 'sign';    // read-only flavour text

/**
 * How the player fires a trigger.
 *   contact — walking into it is enough (doorways, map edges)
 *   confirm — requires the confirm key, with a prompt shown first
 */
export type TriggerActivation = 'contact' | 'confirm';

export interface MapTrigger extends Rect {
  id: string;
  kind: TriggerKind;
  activation: TriggerActivation;
  /** Prompt shown when the player is inside a 'confirm' trigger. */
  prompt?: string;
  targetMapId?: string;
  targetSpawnId?: string;
  dialogueId?: string;
  /** Trigger is inert until this story flag is set. */
  requiresFlag?: string;
  /** Trigger is inert once this story flag is set. */
  consumedByFlag?: string;
  /** Scripted battle payload, for kind === 'battle'. */
  enemyIds?: string[];
  introDialogueId?: string;
  outroDialogueId?: string;
  isBoss?: boolean;
  backgroundColorHex?: string;
}

export interface MapZone extends Rect {
  id: string;
  displayName: string;
  type: 'encounter' | 'safe';
}

export interface MapSpawn {
  id: string;
  x: number;
  y: number;
  /** Facing applied to the player on arrival. */
  facing: 'up' | 'down' | 'left' | 'right';
}

/** A placed sprite: scenery from the object atlas, or a building. */
export interface MapObject {
  id: string;
  /** Atlas key, e.g. 'overworld-objects' or 'structures'. */
  atlas: string;
  /** Frame name within that atlas. */
  frame: string;
  /** World position of the object's bottom-centre origin. */
  x: number;
  y: number;
  /** Draws above the player regardless of y-sorting. */
  above?: boolean;
}

export interface MapNpc {
  id: string;
  /** Character spritesheet key, e.g. 'villager'. */
  sprite: string;
  x: number;
  y: number;
  facing: 'up' | 'down' | 'left' | 'right';
  label: string;
  dialogueId?: string;
  /** Hidden entirely once this flag is set (recruited characters). */
  hideWhenFlag?: string;
}

/** Fully parsed map, ready for a scene to render. */
export interface LoadedMap {
  id: string;
  kind: MapKind;
  displayName: string;
  widthInTiles: number;
  heightInTiles: number;
  tileSize: number;
  widthInPixels: number;
  heightInPixels: number;
  /** Names of tile layers actually present, in render order. */
  tileLayers: TileLayerName[];
  collisionRects: Rect[];
  triggers: MapTrigger[];
  zones: MapZone[];
  spawns: MapSpawn[];
  objects: MapObject[];
  npcs: MapNpc[];
  /** Walk speed override in px/sec; falls back to the kind's default. */
  walkSpeed?: number;
}

/** Data passed into TileMapScene.init(). */
export interface TileMapInitData {
  mapId?: string;
  /** Named spawn point to arrive at. */
  spawnId?: string;
  /** Explicit top-left position, used when resuming a save. */
  startX?: number;
  startY?: number;
}
