// src/game/core/scenes/PreloadScene.ts
// Loads all game assets before TitleScene starts.
// All placeholder visuals are drawn at runtime using Phaser graphics primitives,
// so no assets are loaded yet. This is the correct hook for future sprite/audio loading.

import Phaser from 'phaser';
import { SCENE_KEYS } from '../scene-keys';
import { GAME_WIDTH, GAME_HEIGHT, COLORS, COLOR_HEX, FONTS, FONT_SIZES } from '../config';
import { allMapEntries } from '../../maps/map-registry';

/**
 * Tilesets referenced by the generated maps. The Phaser texture key must equal
 * the tileset name embedded in the Tiled JSON — TileMapScene looks the image up
 * by that name when creating layers.
 */
const TILESETS = ['overworld-terrain', 'interior'] as const;

/** Object atlases, each paired with a manifest holding collision footprints. */
const ATLASES = ['overworld-objects', 'structures'] as const;

/** Character spritesheets generated by the asset pipeline. */
const CHARACTERS = ['hugo', 'villager', 'innkeeper', 'elder'] as const;
const CHARACTER_FRAME = { frameWidth: 48, frameHeight: 64 };

export class PreloadScene extends Phaser.Scene {
  constructor() {
    super({ key: SCENE_KEYS.PRELOAD });
  }

  preload(): void {
    this.createLoadingBar();

    // ── Game assets ───────────────────────────────────────────────────────────
    // Dialogue box background art — 1536×1024 RGBA, displayed at 1200×521.
    // Includes the portrait oval frame (left) and text area (right).
    // All dialogue text is rendered by code on top.
    this.load.image('dialogue-box', 'assets/ui/dialogue-box.png');
    // Result panel background — 1536×1024 RGBA, displayed at 920×613.
    // Text is rendered by code on top; this is decorative background art only.
    this.load.image('result-panel', 'assets/ui/result-panel.png');
    // Command button art — four visual states, 624×256 px source each.
    // Labels are rendered in code on top; these are background art only.
    this.load.image('btn-normal',   'assets/ui/btn-normal.png');
    this.load.image('btn-selected', 'assets/ui/btn-selected.png');
    this.load.image('btn-disabled', 'assets/ui/btn-disabled.png');
    this.load.image('btn-pressed',  'assets/ui/btn-pressed.png');

    // ── Tilemap assets (generated by `npm run assets`) ────────────────────────
    // Tileset images. Keyed by tileset name so TileMapScene can resolve them
    // straight from the name embedded in each map's Tiled JSON.
    for (const name of TILESETS) {
      this.load.image(name, `assets/tilesets/${name}.png`);
    }

    // Object atlases plus their footprint manifests. The manifest is what tells
    // the collision builder that a tree blocks only its trunk.
    for (const name of ATLASES) {
      this.load.atlas(name, `assets/atlases/${name}.png`, `assets/atlases/${name}.json`);
      this.load.json(`${name}-manifest`, `assets/atlases/${name}.manifest.json`);
    }

    // Character spritesheets: 4 walk frames across, 4 directions down.
    for (const name of CHARACTERS) {
      this.load.spritesheet(name, `assets/sprites/${name}.png`, CHARACTER_FRAME);
    }

    // Tiled maps, keyed by map id so TileMapScene can look one up directly.
    for (const entry of allMapEntries()) {
      this.load.tilemapTiledJSON(entry.id, `assets/maps/${entry.file}.json`);
    }
    // ─────────────────────────────────────────────────────────────────────────
  }

  create(): void {
    this.scene.start(SCENE_KEYS.TITLE);
  }

  // ─── Private ───────────────────────────────────────────────────────────────

  private createLoadingBar(): void {
    const cx = GAME_WIDTH / 2;
    const cy = GAME_HEIGHT / 2;

    // Background fill
    this.cameras.main.setBackgroundColor('#0a0f1a');

    // "Loading…" label
    this.add.text(cx, cy - 48, 'Loading...', {
      fontFamily: FONTS.ui,
      fontSize: `${FONT_SIZES.menuButton}px`,
      color: COLOR_HEX.parchment,
    }).setOrigin(0.5);

    // Bar track
    const barW = 400;
    const barH = 20;
    const barX = cx - barW / 2;
    const barY = cy - 10;

    this.add.rectangle(cx, cy + 10, barW + 6, barH + 6, COLORS.panelBorder)
      .setOrigin(0.5);
    this.add.rectangle(cx, cy + 10, barW, barH, COLORS.navyDeep)
      .setOrigin(0.5);

    // Fill bar driven by Phaser's load progress event
    const fill = this.add.rectangle(barX, barY, 0, barH, COLORS.goldAccent)
      .setOrigin(0, 0);

    this.load.on('progress', (value: number) => {
      fill.width = barW * value;
    });
  }
}
