// tools/asset-pipeline/index.mjs
//
// Runs the whole asset pipeline: `npm run assets`.
//
// Everything under public/assets/ is a build output regenerated from the two
// source PNGs in the repository root. The outputs ARE committed (the game
// serves them directly and there is no build-time image step), but they should
// never be hand-edited — change a generator and re-run instead.
//
// The pipeline is deterministic: no Math.random anywhere, all variation comes
// from the hash2/valueNoise helpers in lib/image.mjs. Re-running without source
// or code changes reproduces byte-identical output.

import fs from 'node:fs';
import path from 'node:path';
import { OUT, ROOT, SOURCES, TILE, ensureDirs } from './lib/config.mjs';
import { sliceTerrain, writeTerrainTileset } from './slice-terrain.mjs';
import { buildAutotileSets } from './gen-autotiles.mjs';
import { extractObjects, writeObjectDebugSheet } from './extract-objects.mjs';
import { generateStructures } from './gen-structures.mjs';
import { generateCharacters } from './gen-character.mjs';
import { composeMaps } from './compose-maps.mjs';

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

/** Strips the fields Tiled expects on a standalone tileset but not an embedded one. */
function toEmbedded(tilesetJson) {
  const { type: _type, version: _version, tiledversion: _tiledversion, ...rest } = tilesetJson;
  return rest;
}

function run() {
  const started = Date.now();
  ensureDirs(fs);

  for (const [name, file] of Object.entries(SOURCES)) {
    if (!fs.existsSync(file)) {
      throw new Error(`missing source art for "${name}": ${file}`);
    }
  }

  console.log('Saga asset pipeline');
  console.log(`  tile size: ${TILE}px`);
  console.log(`  sources:   ${Object.values(SOURCES).map(f => path.basename(f)).join(', ')}`);

  console.log('\n[1/6] terrain tileset (File A)');
  const terrain = sliceTerrain();

  console.log('\n[2/6] autotile sets');
  const autotiles = buildAutotileSets(terrain.materials, terrain.shoreColor);
  const { result: terrainResult } = writeTerrainTileset({
    tiles: [...terrain.tiles, ...autotiles],
    groups: terrain.groups,
    shoreColor: terrain.shoreColor,
  });
  console.log(`  overworld-terrain: ${terrainResult.tileCount} tiles, ${terrainResult.width}x${terrainResult.height}px`);

  console.log('\n[3/6] object atlas (File B)');
  const objects = extractObjects();
  writeObjectDebugSheet(objects.objects);

  console.log('\n[4/6] generated structures + interior');
  const structures = generateStructures();

  console.log('\n[5/6] character spritesheets');
  const characters = generateCharacters();

  console.log('\n[6/6] tilemaps');
  const terrainJson = toEmbedded(readJson(path.join(OUT.tilesets, 'overworld-terrain.json')));
  const interiorJson = toEmbedded(readJson(path.join(OUT.tilesets, 'interior.json')));
  const maps = composeMaps({
    terrain: terrainResult,
    terrainJson,
    interior: structures.interior,
    interiorJson,
  });

  // ── Report ────────────────────────────────────────────────────────────────
  const objectManifest = readJson(path.join(OUT.atlases, 'overworld-objects.manifest.json'));
  const report = [
    '# Asset pipeline report',
    '',
    '> Generated by `npm run assets`. Do not edit by hand.',
    '',
    `- Tile size: **${TILE}px**`,
    `- Terrain tileset: **${terrainResult.tileCount}** tiles (${terrain.tiles.length} from File A, ${autotiles.length} generated autotiles)`,
    `- Object atlas: **${objects.objects.length}** sprites extracted from File B`,
    `- Generated structures: **${structures.sprites.length}** sprites`,
    `- Character sheets: **${characters.characters.length}** (${characters.characters.join(', ')})`,
    '',
    '## Object categories',
    '',
    '| Category | Count |',
    '|---|---|',
    ...Object.entries(objectManifest.categories).map(([k, v]) => `| ${k} | ${v} |`),
    '',
    '## Maps',
    '',
    '| File | Id | Kind | Tiles | Pixels | Objects | Triggers | Zones | NPCs |',
    '|---|---|---|---|---|---|---|---|---|',
    ...maps.map(m => `| ${m.file}.json | ${m.id} | ${m.kind} | ${m.tiles} | ${m.pixels} | ${m.objects} | ${m.triggers} | ${m.zones} | ${m.npcs} |`),
    '',
  ].join('\n');

  fs.writeFileSync(path.join(ROOT, 'docs', 'asset-pipeline-report.md'), `${report}\n`);

  console.log(`\nDone in ${((Date.now() - started) / 1000).toFixed(1)}s`);
  console.log('Report: docs/asset-pipeline-report.md');
}

run();
